import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ShareComponents/Navbar";
import Footer from "@/components/ShareComponents/Footer";
import { ToastContainer} from 'react-toastify';
import WhyChooseUs from "@/components/cards/Sections/WhyChooseUs";
import PopularSports from "@/components/cards/Sections/PopularSports";
import FeaturesSection from "@/components/cards/Sections/FeaturesSection";


const josefin = Josefin_Sans({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${josefin.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <ToastContainer autoClose={1000}/>
        <FeaturesSection></FeaturesSection> 
        <WhyChooseUs></WhyChooseUs>
        <PopularSports></PopularSports>
        <main>
           
          {children}
        </main>
        <Footer />
      
      </body>
    </html>
  );
}
